// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuYNmVswMpUN5gYUbLt1un9SWBjcMPaXI',
    appId: '1:636818226950:web:d27b7b4f8e9d139ae92887',
    messagingSenderId: '636818226950',
    projectId: 'socialtinder',
    authDomain: 'socialtinder.firebaseapp.com',
    storageBucket: 'socialtinder.firebasestorage.app',
    measurementId: 'G-2KB7CBN2JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJOTsnn_SqCaZN9lDHQE2W7ukZn2olvz8',
    appId: '1:636818226950:android:f21570359af3e60ce92887',
    messagingSenderId: '636818226950',
    projectId: 'socialtinder',
    storageBucket: 'socialtinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2X2rxykk8rIIf5NvFxlxVLYYMpf6xJmI',
    appId: '1:636818226950:ios:465e38f164b3c51ae92887',
    messagingSenderId: '636818226950',
    projectId: 'socialtinder',
    storageBucket: 'socialtinder.firebasestorage.app',
    iosBundleId: 'com.example.socialTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2X2rxykk8rIIf5NvFxlxVLYYMpf6xJmI',
    appId: '1:636818226950:ios:465e38f164b3c51ae92887',
    messagingSenderId: '636818226950',
    projectId: 'socialtinder',
    storageBucket: 'socialtinder.firebasestorage.app',
    iosBundleId: 'com.example.socialTinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuYNmVswMpUN5gYUbLt1un9SWBjcMPaXI',
    appId: '1:636818226950:web:acd5371f6d58f522e92887',
    messagingSenderId: '636818226950',
    projectId: 'socialtinder',
    authDomain: 'socialtinder.firebaseapp.com',
    storageBucket: 'socialtinder.firebasestorage.app',
    measurementId: 'G-6MCXMPKX3P',
  );
}
